export enum TodoTypes {
  CREATE_TODO_REQUEST = '@todos/CREATE_TODO_REQUEST',
  CREATE_TODO_SUCCESS = '@todos/CREATE_TODO_SUCCESS',
  REMOVE_TODO_REQUEST = '@todos/REMOVE_TODO_REQUEST',
  REMOVE_TODO_SUCCESS = '@todos/REMOVE_TODO_SUCCESS',
}
